# TOML Reference: https://toml.io/en/v1.0.0

# 注意事项：
#   1. 尽量使用内联表，除非导致文本行宽度过宽，此时可采用标准表;
#   2. JSON -> TOML: brew install yj && cat package.json | yj -jt;
#      TOML -> JSON: cat redevelop.b2c.toml | yj -tj -i;
#   3. VS Code 插件推荐: Even Better TOML;

# 临时二开仓库存放目录
redevRepoPath = '/Users/hustcer/redev-repos'

# 当前要打的后端版本号标签
redevCurrentTag = 'v2.2.x'

# 待比较差异的前一个标签完整名称
redevPrevTag = 'v2.2.0.9-2021.09.23'

# 新增的二开标签备注
redevTagComment = 'This is a release tag'

# 远程二开仓库地址
redevRepos = [
  # https://erda.cloud/terminus/dop/projects/385/apps/6898/repo/tags
  { name = 'b2b-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6899/repo/tags
  { name = 'b2b-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6896/repo/tags
  { name = 'b2c-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6897/repo/tags
  { name = 'b2c-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6857/repo/tags
  { name = 'b2c-mobile-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6871/repo/tags
  { name = 'b2c-mobile-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6994/repo/tags
  { name = 'sea-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6995/repo/tags
  { name = 'sea-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6992/repo/tags
  { name = 'sea-mobile-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6993/repo/tags
  { name = 'sea-mobile-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7422/repo/tags
  { name = 'gaia-picker-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7423/repo/tags
  { name = 'gaia-picker-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev-origin' },
]

# Set currentSelected to change the shell to execute the command
# 'SHELL_TO_RUN_CMD' var in .env has higher priority
[shellToRunCmd]
nu = '-c'
sh = '-cu'
cmd = '/c'
bash = '-c'
powershell = '-c'
currentSelected = 'bash'
