# Run the container with: docker compose up
# Or for a one-time run: docker compose run --rm termix
# Home dir of termix-nu in the container: /home/termix/termix-nu
services:
  termix:
    tty: true
    stdin_open: true
    pull_policy: if_not_present
    image: hustcer/termix:latest
    volumes:
      # - ./.env:/home/termix/.env
      - ./.termixrc:/home/termix/.termixrc
