[[repos]]
name = "@terminus/react-navigation-bottom-tabs"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/rollup-plugin-alias"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/typescript-checker"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/bricks"
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/frontend-product/bricks"
url = "https://erda.cloud/terminus/dop/projects/213/apps/5317/repo"

[[repos]]
name = "@terminus/designer"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/designer/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee-config-plugin"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee-config-plugin/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/site-manager"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/site-manager/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/termix"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/termix/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mall-base"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/mall-base/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mall-utils"
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/mall-utils/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mp-barcode"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/4205/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mp-barcode"

[[repos]]
name = "@terminus/mp-calendar"
tagged = true
monoRepo = false
srcPublished = true
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/4206/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mp-calendar"

[[repos]]
name = "@terminus/octopus-cli"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/cli/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-core"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/core/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-jssdk"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/jssdk/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-shared"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/shared/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/react-native-octopus"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/react-native-octopus/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/rollup-plugin-typescript"
tagged = true
monoRepo = true
downloadable = true
srcPublished = false
pkgFile = "packages/typescript/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/trnw-design"
tagged = true
monoRepo = false
downloadable = true
srcPublished = false
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003444/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-design"

[[repos]]
name = "@terminus/trnw-package-tools"
tagged = true
monoRepo = false
downloadable = true
srcPublished = false
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003446/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-package-tools"

[[repos]]
name = "@terminus/trnw-tools"
tagged = true
monoRepo = false
srcPublished = true
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003445/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-tools"

[[repos]]
name = "@terminus/react-native-amap-sdk"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5236/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-amap"

[[repos]]
name = "@terminus/rn-b2b2c"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5308/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-b2b2c"

[[repos]]
name = "@terminus/react-native-camera"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5264/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-camera"

[[repos]]
name = "@terminus/rn-share"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5261/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-share"

[[repos]]
name = "@terminus/nusi-slim"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-nusi/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/react-imageview"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/170/apps/5492/repo"
repo = "https://erda.cloud/terminus/dop/nusi/react-imageview"

[[repos]]
name = "@terminus/react-underline-tabbar"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/170/apps/4773/repo"
repo = "https://erda.cloud/terminus/dop/nusi/react-underline-tabbar"
