[[repos]]
name = "@terminus/react-navigation-bottom-tabs"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/rollup-plugin-alias"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/typescript-checker"
repo = ""
monoRepo = false
srcPublished = true
downloadable = true

[[repos]]
name = "@terminus/bricks"
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/frontend-product/bricks"
url = "https://erda.cloud/terminus/dop/projects/213/apps/5317/repo"

[[repos]]
name = "@terminus/designer"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/designer/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee-config-plugin"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee-config-plugin/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/site-manager"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/site-manager/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/hot-area-editor"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/hot-area-editor/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee-react-components"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee-components-react/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/eevee-client-engine-react"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/eevee-client-engine-react/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4220/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/eevee"

[[repos]]
name = "@terminus/herd"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/5413/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/herd"

[[repos]]
name = "@terminus/herd-core"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/5423/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/herd-core"

[[repos]]
name = "@terminus/jarvisplus"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/jarvisplus/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/9954/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/jarvisplus"

[[repos]]
name = "@terminus/jarvisplus-runtime"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/jarvisplus-runtime/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/9954/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/jarvisplus"

[[repos]]
name = "@terminus/koa2-file-upload"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/7452/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/koa2-file-upload"

[[repos]]
name = "@terminus/termix"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/termix/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mall-base"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/mall-base/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mall-utils"
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/mall-utils/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4280/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mall-base"

[[repos]]
name = "@terminus/mp-barcode"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/4205/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mp-barcode"

[[repos]]
name = "@terminus/mp-calendar"
tagged = true
monoRepo = false
srcPublished = true
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/4206/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/mp-calendar"

[[repos]]
name = "@terminus/octopus-cli"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/cli/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-core"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/core/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-jssdk"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/jssdk/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-shared"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/shared/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/react-native-octopus"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/react-native-octopus/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/rollup-plugin-typescript"
tagged = true
monoRepo = true
downloadable = true
srcPublished = false
pkgFile = "packages/typescript/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-router"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/router/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-hooks"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/hooks/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/octopus-polyfill"
tagged = true
monoRepo = true
downloadable = true
pkgFile = "packages/polyfill/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/4847/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/octopus"

[[repos]]
name = "@terminus/parkball"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/3370/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/parkball"

[[repos]]
name = "@terminus/react-native-web"
tagged = false
monoRepo = true
downloadable = true
pkgFile = "packages/react-native-web/package.json"
url = "https://erda.cloud/terminus/dop/projects/213/apps/6099/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/react-native-web"

[[repos]]
name = "@terminus/react-navigation"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/4569/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/react-navigation"

[[repos]]
name = "@terminus/rn-template"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/7859/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/rn-template"

[[repos]]
name = "@terminus/invokers"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/5425/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/terminus-invokers"

[[repos]]
name = "@terminus/trnw-design"
tagged = true
monoRepo = false
downloadable = true
srcPublished = false
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003444/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-design"

[[repos]]
name = "@terminus/trnw-package-tools"
tagged = true
monoRepo = false
downloadable = true
srcPublished = false
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003446/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-package-tools"

[[repos]]
name = "@terminus/trnw-tools"
tagged = true
monoRepo = false
srcPublished = true
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/213/apps/1003445/repo"
repo = "https://erda.cloud/terminus/dop/frontend-product/trnw-tools"

[[repos]]
name = "@terminus/react-native-amap-sdk"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5236/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-amap"

[[repos]]
name = "@terminus/rn-b2b2c"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5308/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-b2b2c"

[[repos]]
name = "@terminus/react-native-camera"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5264/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-camera"

[[repos]]
name = "@terminus/rn-share"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/254/apps/5261/repo"
repo = "https://erda.cloud/terminus/dop/mobile/react-native-share"

[[repos]]
name = "@terminus/nusi"
tagged = true
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/nusi"
url = "https://erda.cloud/terminus/dop/projects/170/apps/2727/repo"

[[repos]]
name = "@terminus/nusi-flex"
tagged = true
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/nusi-flex"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11688/repo"

[[repos]]
name = "@terminus/nusi-icons"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/icons/package.json"
url = "https://erda.cloud/terminus/dop/projects/170/apps/3389/repo"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-icons"

[[repos]]
name = "@terminus/nusi-icons-react"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "packages/icons-react/package.json"
url = "https://erda.cloud/terminus/dop/projects/170/apps/3389/repo"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-icons"

[[repos]]
name = "@terminus/nusi-mobile"
tagged = true
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/nusi-mobile"
url = "https://erda.cloud/terminus/dop/projects/170/apps/4419/repo"

[[repos]]
name = "@terminus/nusi-pos"
tagged = false
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/nusi-pos"
url = "https://erda.cloud/terminus/dop/projects/170/apps/6372/repo"

[[repos]]
name = "@terminus/nusi-slim"
tagged = true
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-nusi/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/fn-editor"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-editor/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/nusi-slim-icons"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-icon/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/nusi-slim-plugin"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-plugin/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/nusi-preview"
tagged = false
monoRepo = true
standalone = true
downloadable = true
pkgFile = "pkg-preview/package.json"
repo = "https://erda.cloud/terminus/dop/nusi/nusi-slim"
url = "https://erda.cloud/terminus/dop/projects/170/apps/11930/repo"

[[repos]]
name = "@terminus/rc-form"
tagged = false
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/170/apps/3664/repo"
repo = "https://erda.cloud/terminus/dop/nusi/rc-form"

[[repos]]
name = "@terminus/react-imageview"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/170/apps/5492/repo"
repo = "https://erda.cloud/terminus/dop/nusi/react-imageview"

[[repos]]
name = "@terminus/react-native-snap-carousel"
tagged = false
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/react-native-snap-carousel"
url = "https://erda.cloud/terminus/dop/projects/170/apps/9311/repo"

[[repos]]
name = "@terminus/react-underline-tabbar"
tagged = true
monoRepo = false
downloadable = true
url = "https://erda.cloud/terminus/dop/projects/170/apps/4773/repo"
repo = "https://erda.cloud/terminus/dop/nusi/react-underline-tabbar"

[[repos]]
name = "@terminus/rmc-calendar"
tagged = false
monoRepo = false
downloadable = true
repo = "https://erda.cloud/terminus/dop/nusi/rmc-calendar"
url = "https://erda.cloud/terminus/dop/projects/170/apps/5562/repo"
