# TOML Reference: https://toml.io/en/v1.0.0

# 注意事项：
#   1. 尽量使用内联表，除非导致文本行宽度过宽，此时可采用标准表;
#   2. JSON -> TOML: brew install yj && cat package.json | yj -jt;
#      TOML -> JSON: cat redevelop.b2c.toml | yj -tj -i;
#   3. VS Code 插件推荐: Even Better TOML;

# Termix-nu version
version = 'v1.91.0'

# Min nushell version required to run termix-nu commands
minNuVer = '0.106.0'

# Min just version required to run termix-nu commands
minJustVer = '1.39.0'

# Min @terminus/t-package-tools version required to sync terp assets
minPkgToolVer = '0.5.5'

# 新增的二开标签备注
redevTagComment = 'This is a release tag'

# .termixrc 配置从哪个分支上读取？`_current_` 代表当前所在 git 分支, `i` 表示全局 i 分支
useConfFromBranch = 'i'

# [√] 支持仓库分组？
# [ ] 添加 enable 字段?
# 远程二开仓库地址
redevRepos = [
  # https://erda.cloud/terminus/dop/projects/385/apps/6896/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6897/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6994/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6995/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8112/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8113/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8114/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-oversea-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8115/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-oversea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6857/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6871/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6992/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6993/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8345/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-point-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8346/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-point-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8318/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8319/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8320/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-oversea-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8321/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-oversea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8316/repo
  { group = 'mbr', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-mbr-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8317/repo
  { group = 'mbr', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-mbr-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8166/repo
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8167/repo
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6898/repo/tags
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6899/repo/tags
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7422/repo/tags
  { group = 'pik', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7423/repo/tags
  { group = 'pik', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev-origin' },
]

# 标品前端远程源码仓库配置，供标品打 Release Tag 之用
gaiaSrcRepos = [
  { name = 'gaia-mall', branch = 'release/redevelop', suffix = '', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mall' },
  { name = 'gaia-mobile', branch = 'release/redevelop', suffix = '', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mobile' },
  { name = 'gaia-picker', branch = 'release/redevelop', suffix = '', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-picker' },
]

[TERP_CONFIG_TIPS]
terp-assets = """
                    (ansi r)客户项目务必处理此问题 ！！！(ansi rst)
TERP Assets 低修改频率静态资源初始化配置方法(上传一次，后续几乎不会再变):

静态资源初始化可以使用 termix-nu 工具的 (ansi p)`t ta init` (ansi rst)命令，该静态资源的初始化是 Bucket 级别的，
跟环境无关，每个 Bucket 里面初始化一份然后配置好网关转发就可以了，所以初始化参数里面只有 (ansi p)`-d` (ansi rst)
OR (ansi p)`--dest-store` (ansi rst), 例如:

(ansi p)`t ta init -d oss`(ansi rst), 其中 oss 在 (ansi g).termixrc(ansi rst) 中配置(可参考 .termixrc-example), 内容大致如下:
(ansi p)
```toml
(ansi gr)# OSS 配置(ansi rst)
(ansi p)oss.TYPE = 'aliyun'
oss.OSS_AK = 'YOUR-OSS-AK'
oss.OSS_SK = 'YOUR-OSS-SK'
oss.OSS_BUCKET = 'YOUR-BUCKET-NAME'
oss.OSS_REGION = 'oss-cn-hangzhou'
oss.OSS_ENDPOINT = 'https://oss-cn-hangzhou.aliyuncs.com'(ansi rst)
```
注意：对于 Toml 文件来说配置项的位置是很重要的，不要随意移动，否则会导致配置项失效

初始化成功后在对应 Bucket 的 terp-assets 目录下可以找到对应的静态资源。然后需要配置网关转发,
以下是阿里云存储配置示例(以 TERP 标品举例，其他按需调整)：

URL 路径前缀: (ansi y)/terp-assets(ansi rst)
    转发方式: 选择 (ansi y)按地址转发(ansi rst)
    转发地址: (ansi y)http:// (ansi gr),(ansi rst) (ansi y)terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com(ansi rst)
    API 前缀: (ansi y)/terp-assets(ansi rst)
    调用方法: (ansi y)GET(ansi rst)
        描述: (ansi y)PDF字体、XLSX JS等静态资源转发配置(ansi rst)
        注意: (ansi g)对应的前端 Console, Portal 应用都需要配置，若有 H5 应用也需要配置 Portal H5(ansi rst)
              (ansi g)配置完毕后可以通过 `t doctor $host` 命令进行检查(ansi rst)
"""
latest-gateway = """

TERP latest.json 网关转发配置方法:

在完成标品静态资源同步后，可以通过 Erda 网关对静态资源进行转发, 配置示例:

URL 路径前缀: (ansi y)/latest.json(ansi rst)
    转发方式: 选择 (ansi y)按地址转发(ansi rst)
    转发地址: 在线文件存储地址, 强烈建议配置客户文件存储服务地址
              比如: (ansi y)http:// (ansi gr),(ansi rst) (ansi y)terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com(ansi rst)
    API 前缀: (ansi y)/fe-resources/${mount_point}/latest.json(ansi rst)
    调用方法: (ansi y)GET(ansi rst)
        描述: (ansi y)latest.json(ansi rst)
        注意: (ansi g)对应的前端 Console, Portal 应用都需要配置，若有 H5 应用也需要配置 Portal H5(ansi rst)
              (ansi g)配置完毕后可以通过 `t doctor $host` 命令进行检查(ansi rst)
"""
latest-endpoint = """

TERP latest.json Nginx 业务策略配置方法:

在 latest.json 的业务策略配置里开启规则，并在自定义 Nginx 配置里面添加如下内容:

```nginx
(ansi p)add_header 'x-trantor-endpoint' '${项目的oss}';(ansi rst)
(ansi gr)# MinIO 示例:
# add_header 'x-trantor-endpoint' 'https://minio-server.fly.com/fly-prod';
# AliYun OSS 示例:
# add_header 'x-trantor-endpoint' 'https://fly-erp.oss-cn-hangzhou.aliyuncs.com';(ansi rst)
```
只有静态资源存储在 https://terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com Bucket 才
可以不配置，其他 OSS Bucket 或云存储都需要配置, 否则会导致静态资源加载失败。
"""

[empWorkingHour]
leaveUrl = 'https://emp-portal.app.terminus.io/api/trantor/service/engine/execute/MD$get_employee_leave_info'
timeUrl = 'https://emp-portal.app.terminus.io/api/trantor/service/engine/execute/WORKTIME$get_employee_project_hours_within_specified_time'
staffUrl = 'https://emp-portal.app.terminus.io/api/trantor/service/engine/execute/WORKTIME$get_department_employees_with_work_hour_filter'
timeSummaryUrl = 'https://emp-portal.app.terminus.io/api/trantor/service/engine/execute/WORKTIME$department_employees_work_hours_data_status_statis'
allStaffUrl = 'https://emp-portal.app.terminus.io/api/trantor/service/engine/execute/PROJECT$SYS_PagingDataService?tmodule=&modelKey=MD%24md__staff_b_o'

# 快捷导航
[quickNavs]
nusi-slim = 'https://nusi-slim.app.terminus.io/'
nusi-flex = 'https://nusi-flex.app.terminus.io/'
termix-nu = 'https://fe-docs.app.terminus.io/termix/termix-nu'

# Set currentSelected to change the shell to execute the command
# 'SHELL_TO_RUN_CMD' var in .env has higher priority
[shellToRunCmd]
nu = '-c'
sh = '-c'
cmd = '/c'
zsh = '-uc'
fish = '-c'
node = '-e'
bash = '-uc'
python3 = '-c'
powershell = '-c'
currentSelected = 'bash'
