# TOML Reference: https://toml.io/en/v1.0.0

# 注意事项：
#   1. 尽量使用内联表，除非导致文本行宽度过宽，此时可采用标准表;
#   2. JSON -> TOML: brew install yj && cat package.json | yj -jt;
#      TOML -> JSON: cat redevelop.b2c.toml | yj -tj -i;
#   3. VS Code 插件推荐: Even Better TOML;

# Termix-nu version
version = 'v1.2.6'

# Min nushell version required to run termix-nu commands
minNuVer = '0.40.0'

# Min just version required to run termix-nu commands
minJustVer = '0.10.5'

# 临时二开仓库存放目录, .env 里面 TERMIX_TMP_PATH 具有更高优先级
termixTmpPath = '/Users/hustcer/.termix-nu'

# 新增的二开标签备注
redevTagComment = 'This is a release tag'

# .termixrc 配置从哪个分支上读取？`_current_` 代表当前所在 git 分支, `i` 表示全局 i 分支
useConfFromBranch = 'i'

# [ ] 支持仓库分组？
# [ ] 添加 enable 字段?
# [ ] REDEV_GIT_PREFIX = https://erda.cloud/terminus/dop/gaia-app-redev/
# 远程二开仓库地址
redevRepos = [
  # https://erda.cloud/terminus/dop/projects/385/apps/6898/repo/tags
  { name = 'b2b-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6899/repo/tags
  { name = 'b2b-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6896/repo/tags
  { name = 'b2c-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6897/repo/tags
  { name = 'b2c-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6857/repo/tags
  { name = 'b2c-mobile-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6871/repo/tags
  { name = 'b2c-mobile-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6994/repo/tags
  { name = 'sea-mall-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6995/repo/tags
  { name = 'sea-mall-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6992/repo/tags
  { name = 'sea-mobile-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6993/repo/tags
  { name = 'sea-mobile-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7422/repo/tags
  { name = 'gaia-picker-all', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7423/repo/tags
  { name = 'gaia-picker-origin', url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev-origin' },
]

# 标品前端远程源码仓库配置，供标品打 Release Tag 之用
gaiaSrcRepos = [
  { name = 'gaia-mall', branch = 'release/redevelop', suffix = '', url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mall' },
  { name = 'gaia-mobile', branch = 'release/sea', suffix = 'sea', url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mobile' },
  { name = 'gaia-mobile', branch = 'release/redevelop', suffix = '', url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mobile' },
  { name = 'gaia-picker', branch = 'release/redevelop', suffix = '', url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-picker' },
]

[empWorkingHour]
url = 'https://gateway.app.terminus.io/compass/emp/emp-project/api/trantor/data-source'
type = 'Content-Type: application/json'
cookie = 'Cookie: emp_u_c_local=_EMP_UC_COOKIE_'
payload = '{"targetModel":"emp_project_WeekWorkTime","queryValues":{"outerId":{"type":"One","value":_outer_id_},"year":{"type":"One","value":_current_year_},"week":{"type":"One","value":_week_no_}},"dataSource":{"actionKey":"emp_project_WeekWorkTime_departmentWorkTimeList"}}'

# 快捷导航
[quickNavs]
base = 'https://erda.cloud/terminus/dop/projects/213/apps/4280/repo'
docs = 'https://erda.cloud/terminus/dop/projects/213/apps/7542/repo'
nusi-mobile = 'https://erda.cloud/terminus/dop/projects/170/apps/4419/repo'
src-mall = 'https://erda.cloud/terminus/dop/projects/385/apps/6123/repo'
src-mobile = 'https://erda.cloud/terminus/dop/projects/385/apps/6125/repo'
src-picker = 'https://erda.cloud/terminus/dop/projects/385/apps/6388/repo'
mix-sea = 'https://erda.cloud/terminus/dop/projects/420/apps/7190/repo'
mix-mall = 'https://erda.cloud/terminus/dop/projects/420/apps/6701/repo'
mix-mobile = 'https://erda.cloud/terminus/dop/projects/420/apps/6699/repo'
mix-m-sea = 'https://erda.cloud/terminus/dop/projects/420/apps/7400/repo'
mix-m-point = 'https://erda.cloud/terminus/dop/projects/420/apps/7807/repo'
mix-b2b = 'https://erda.cloud/terminus/dop/projects/420/apps/7522/repo'
mix-srm = 'https://erda.cloud/terminus/dop/projects/420/apps/7523/repo'
mix-m-b2b = 'https://erda.cloud/terminus/dop/projects/420/apps/7839/repo'
mix-m-srm = 'https://erda.cloud/terminus/dop/projects/420/apps/8088/repo'
mix-m-mbr = 'https://erda.cloud/terminus/dop/projects/420/apps/7591/repo'
bbc-mall = 'https://erda.cloud/terminus/dop/projects/394/apps/6124/repo'
bbc-sea = 'https://erda.cloud/terminus/dop/projects/394/apps/6674/repo'
bbc-mobile = 'https://erda.cloud/terminus/dop/projects/394/apps/6113/repo'
bbc-m-sea = 'https://erda.cloud/terminus/dop/projects/394/apps/6675/repo'
bbc-picker = 'https://erda.cloud/terminus/dop/projects/394/apps/6387/repo'
mix-picker = 'https://erda.cloud/terminus/dop/projects/420/apps/7403/repo'

# Set currentSelected to change the shell to execute the command
# 'SHELL_TO_RUN_CMD' var in .env has higher priority
[shellToRunCmd]
nu = '-c'
sh = '-c'
cmd = '/c'
zsh = '-uc'
fish = '-c'
node = '-e'
bash = '-uc'
python3 = '-c'
powershell = '-c'
currentSelected = 'bash'
