# TOML Reference: https://toml.io/en/v1.0.0

# 注意事项：
#   1. 尽量使用内联表，除非导致文本行宽度过宽，此时可采用标准表;
#   2. JSON -> TOML: brew install yj && cat package.json | yj -jt;
#      TOML -> JSON: cat redevelop.b2c.toml | yj -tj -i;
#   3. VS Code 插件推荐: Even Better TOML;

# Termix-nu version
version = 'v1.18.0'

# Min nushell version required to run termix-nu commands
minNuVer = '0.80.0'

# Min just version required to run termix-nu commands
minJustVer = '1.13.0'

# 临时二开仓库存放目录, .env 里面 TERMIX_TMP_PATH 具有更高优先级
termixTmpPath = '/Users/hustcer/.termix-nu'

# 新增的二开标签备注
redevTagComment = 'This is a release tag'

# .termixrc 配置从哪个分支上读取？`_current_` 代表当前所在 git 分支, `i` 表示全局 i 分支
useConfFromBranch = 'i'

# [√] 支持仓库分组？
# [ ] 添加 enable 字段?
# 远程二开仓库地址
redevRepos = [
  # https://erda.cloud/terminus/dop/projects/385/apps/6896/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6897/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6994/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6995/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8112/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8113/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8114/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-oversea-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8115/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-brand-oversea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6857/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6871/repo/tags
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2c-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6992/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6993/repo/tags
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-sea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8345/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-point-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8346/repo
  { group = 'b2c', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-point-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8318/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8319/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8320/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-oversea-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8321/repo
  { group = 'b2c', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-brand-oversea-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8316/repo
  { group = 'mbr', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-mbr-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8317/repo
  { group = 'mbr', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-mbr-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8166/repo
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/691/apps/8167/repo
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mobile-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6898/repo/tags
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/6899/repo/tags
  { group = 'b2b', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-mall-b2b-redev-origin' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7422/repo/tags
  { group = 'pik', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev' },
  # https://erda.cloud/terminus/dop/projects/385/apps/7423/repo/tags
  { group = 'pik', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app-redev/gaia-picker-redev-origin' },
]

# 标品前端远程源码仓库配置，供标品打 Release Tag 之用
gaiaSrcRepos = [
  { name = 'gaia-mall', branch = 'release/redevelop', suffix = '', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mall' },
  { name = 'gaia-mobile', branch = 'release/redevelop', suffix = '', enable = true, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-mobile' },
  { name = 'gaia-picker', branch = 'release/redevelop', suffix = '', enable = false, url = 'https://erda.cloud/terminus/dop/gaia-app/gaia-picker' },
]

[empWorkingHour]
app = 'x-trantor-app: emp_worktime'
type = 'Content-Type: application/json'
cookie = 'Cookie: emp_u_c_local=_EMP_UC_COOKIE_'
timeUrl = 'https://gateway.app.terminus.io/compass/emp-worktime/worktime/17096/api/trantor/func/worktime_GetStaffWorkTimeFunc'
leaveUrl = 'https://gateway.app.terminus.io/compass/emp-worktime/worktime/17096/api/trantor/func/worktime_GetEmployeeLeaveInfoFunc'
staffUrl = 'https://gateway.app.terminus.io/compass/emp-worktime/worktime/17096/api/trantor/func/worktime_GetStaffByBaseProjectFunc'
timePayload = '[{"beginDate":"_first_day_","endDate":"_last_day_","staffs": _staffs_}]'
leavePayload = '[{"beginDate":"_first_day_","endDate":"_last_day_","staffBOS": _staffs_}]'
staffPayload = '[{"beginDate":"_first_day_","endDate":"_last_day_","baseProjectTOS":[{"type":"DEPARTMENT","projectCode":"_project_code_"}]}]'

# 快捷导航
[quickNavs]
base = 'https://erda.cloud/terminus/dop/projects/213/apps/4280/repo'
docs = 'https://erda.cloud/terminus/dop/projects/213/apps/7542/repo'
nusi-mobile = 'https://erda.cloud/terminus/dop/projects/170/apps/4419/repo'
src-mall = 'https://erda.cloud/terminus/dop/projects/385/apps/6123/repo'
src-mobile = 'https://erda.cloud/terminus/dop/projects/385/apps/6125/repo'
src-picker = 'https://erda.cloud/terminus/dop/projects/385/apps/6388/repo'
mix-sea = 'https://erda.cloud/terminus/dop/projects/420/apps/7190/repo'
mix-mall = 'https://erda.cloud/terminus/dop/projects/420/apps/6701/repo'
mix-mobile = 'https://erda.cloud/terminus/dop/projects/420/apps/6699/repo'
mix-m-sea = 'https://erda.cloud/terminus/dop/projects/420/apps/7400/repo'
mix-m-point = 'https://erda.cloud/terminus/dop/projects/420/apps/7807/repo'
mix-b2b = 'https://erda.cloud/terminus/dop/projects/420/apps/7522/repo'
mix-srm = 'https://erda.cloud/terminus/dop/projects/420/apps/7523/repo'
mix-m-b2b = 'https://erda.cloud/terminus/dop/projects/420/apps/7839/repo'
mix-m-srm = 'https://erda.cloud/terminus/dop/projects/420/apps/8088/repo'
mix-m-mbr = 'https://erda.cloud/terminus/dop/projects/420/apps/7591/repo'
bbc-mall = 'https://erda.cloud/terminus/dop/projects/394/apps/6124/repo'
bbc-sea = 'https://erda.cloud/terminus/dop/projects/394/apps/6674/repo'
bbc-mobile = 'https://erda.cloud/terminus/dop/projects/394/apps/6113/repo'
bbc-m-sea = 'https://erda.cloud/terminus/dop/projects/394/apps/6675/repo'
bbc-picker = 'https://erda.cloud/terminus/dop/projects/394/apps/6387/repo'
mix-picker = 'https://erda.cloud/terminus/dop/projects/420/apps/7403/repo'

# Set currentSelected to change the shell to execute the command
# 'SHELL_TO_RUN_CMD' var in .env has higher priority
[shellToRunCmd]
nu = '-c'
sh = '-c'
cmd = '/c'
zsh = '-uc'
fish = '-c'
node = '-e'
bash = '-uc'
python3 = '-c'
powershell = '-c'
currentSelected = 'bash'
